### PR TITLE
Can you work on this

### PR DESCRIPTION
**Pull request by piliatchoo**
Could you work on this as it is in with standerd hud qbus
ui.lua
stress.lua
with default qb-hud
not running perfect ?

### CODE REVIEW

**Comment by XiosBombay** [comment]
So what do you want me to do?

**Comment by Plaza31** [comment]
Are you able to make it so the options that you have saved aka when you move the hud around like the little circles etc they don't save when you relog.

**Comment by ircmage** [comment]
can add seatbelt?

**Comment by RockySouthpaw** [comment]
This is not being merged. This PR consist of breaking changes that would essentially make QBCore a dependency. Furthermore, it’s clearly still a WIP adaptation.

If you have a suggestion then make a suggestion under the issues category please :), not a lull request.

**Pull request closed without merging**
