### PR TITLE
Fix food & water not show up

### PR DESCRIPTION
**Pull request by hichay**
This help fix esx food and water >

### CODE REVIEW

**Comment by XiosBombay** [comment]
What is the difference between the current one and this one? Mine seems to work fine too.

**Comment by hichay** [comment]
> What is the difference between the current one and this one? Mine seems to work fine too.

on my version it not work. even it with original status

**Comment by XiosBombay** [comment]
`on my version it not work. even it with original status`
On mine it seems to work fine. I'll test your version later today for performance.

I have two questions.
**What ESX version are you using?**
**Where did you get the esx_status from?**

**Comment by hichay** [comment]
> > on my version it not work. even it with original status
> 
> On mine it seems to work fine. I'll test your version later today for performance.
> 
> I have two questions.
> **What ESX version are you using?**
> **Where did you get the esx_status from?**

i use the EXM and the unstable esx_status

**Comment by hichay** [comment]
> > i use the EXM and the unstable esx_status
> 
> I have no idea what the unstable esx_status is. Do you mind sending me a link?

https://github.com/esx-framework/esx_status this one

**Comment by RockySouthpaw** [comment]
> > > i use the EXM and the unstable esx_status
> > 
> > 
> > I have no idea what the unstable esx_status is. Do you mind sending me a link?
> 
> https://github.com/esx-framework/esx_status this one

How in the world is this unstable esx_status?

I also couldn't reproduce the issue you were experiencing.

**Comment by hichay** [comment]
I have no idea. i got problem with the food and water. and my way fix it

**Comment by XiosBombay** [comment]
Closing this since there will be breaking changes.

**Pull request closed without merging**
